#!/bin/bash

# Source color palette
source ~/.config/theme/colors.sh

# --- Helper function: convert hex -> R G B ---
hex_to_rgb() {
  local hex="${1#"#"}"
  printf "%d %d %d" "$((16#${hex:0:2}))" "$((16#${hex:2:2}))" "$((16#${hex:4:2}))"
}

# --- Convert alpha (0–1 float) → two-digit hex (00–FF) ---
alpha_to_hex() {
  local alpha=$1
  local value=$(awk -v a="$alpha" 'BEGIN { printf "%02X", int(a * 255 + 0.5) }')
  echo "$value"
}

ALPHA_HEX=$(alpha_to_hex "$ALPHA")

# === Generate Kitty Config ===
cat >~/.config/kitty/kitty_colors.conf <<EOF
# Auto-generated by apply_theme.sh
background                #$BG
background_opacity        $ALPHA
foreground                #$FG
cursor                    #$FG
selection_background      #$color0
selection_foreground      #$FG

color0                    #$color0
color1                    #$color1
color2                    #$color2
color3                    #$color3
color4                    #$color4
color5                    #$color5
color6                    #$color6
color7                    #$color7
color8                    #$color8
color9                    #$color9
color10                   #$color10
color11                   #$color11
color12                   #$color12
color13                   #$color13
color14                   #$color14
color15                   #$color15
EOF

read -r R G B <<<"$(hex_to_rgb "$BG")"

# === Generate Rofi Config ===
cat >~/.config/rofi/rofi_colors.rasi <<EOF
/* Auto-generated by apply_theme.sh */

* {
    bg:      rgba(${R}, ${G}, ${B}, ${ALPHA});
    fg:      #$FG;
    border:  #$BORDER;

    black:   #$color0;
    red:     #$color1;
    green:   #$color2;
    yellow:  #$color3;
    blue:    #$color4;
    magenta: #$color5;
    cyan:    #$color6;
    white:   #$color7;

    color0:  #$color0;
    color1:  #$color1;
    color2:  #$color2;
    color3:  #$color3;
    color4:  #$color4;
    color5:  #$color5;
    color6:  #$color6;
    color7:  #$color7;
    color8:  #$color8;
    color9:  #$color9;
    color10: #$color10;
    color11: #$color11;
    color12: #$color12;
    color13: #$color13;
    color14: #$color14;
    color15: #$color15;
}
EOF

# === Generate Waybar Config ===
cat >~/.config/waybar/waybar_colors.css <<EOF
/* Auto-generated by apply_theme.sh */

/* Main colors */
@define-color bg      rgba(${R}, ${G}, ${B}, ${ALPHA});
@define-color fg      #$FG;
@define-color border  #$BORDER;

/* Semantic mapping */
@define-color black   #$color0;
@define-color red     #$color1;
@define-color green   #$color2;
@define-color yellow  #$color3;
@define-color blue    #$color4;
@define-color magenta #$color5;
@define-color cyan    #$color6;
@define-color white   #$color7;

/* Direct numbered mapping */
@define-color color0  #$color0;
@define-color color1  #$color1;
@define-color color2  #$color2;
@define-color color3  #$color3;
@define-color color4  #$color4;
@define-color color5  #$color5;
@define-color color6  #$color6;
@define-color color7  #$color7;
@define-color color8  #$color8;
@define-color color9  #$color9;
@define-color color10 #$color10;
@define-color color11 #$color11;
@define-color color12 #$color12;
@define-color color13 #$color13;
@define-color color14 #$color14;
@define-color color15 #$color15;
EOF

# === Reload ===
echo "Reloading services..."
kitty @ set-colors --all ~/.config/kitty/kitty_colors.conf
pkill -SIGUSR2 waybar
echo "Theme applied!"
